apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo 'hello from pvc' > /data/test.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: mypod
  volumes:
    - name: mypod
      persistentVolumeClaim:
        claimName: myclaim
