apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base
images:
  - name: sarif
    newTag: local
patches:
  - path: configmap-cors-patch.yaml
  - path: ingress-patch.yaml
